### ISSUE TITLE
Set path for Split-seq_Sai , Error message : cp: cannot stat /Split*.sh': No such file or directory cp: missing destination file operand after '

### ISSUE THREAD

**Issue by whuang022nccu** [masai1116/SHARE-seq-alignmentV2#1]
Dear Mr. Ma : 

I am trying to install SHARE-seq-alignmentV2 , however  I got some issues to setting 'myPath' to point to 'Split-seq_Sai' , where can I install Split-seq_Sai  or what shold I put for the 'myPath' ? This is how I set my pathes:

<a href="https://ibb.co/LQVnv1G"><img src="https://i.ibb.co/3fgBkcJ/gnome-shell-screenshot-Q3-C8-N1.png" alt="gnome-shell-screenshot-Q3-C8-N1" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>temporary image hosting</a><br /> 

error I got :  

<a href="https://ibb.co/G0NMqht"><img src="https://i.ibb.co/JKgp9hy/image.png" alt="image" border="0"></a><br /><a target='_blank' href='https://imgbb.com/'>quick image upload</a><br />

csused from:

![image](https://user-images.githubusercontent.com/48216039/175860444-70b28c83-92cb-4936-9f17-7d3620bafa6d.png)

Thanks for your help.

Sincerely,

**Comment by masai1116** [comment]
Hey,

Nice catch. There is a small bug in the Share_seqV2_example.sh script. I
just made a quick fix. This should fix the first error you saw "cp: cannot
stat ...." This error shouldn't affect anything downstream though.
For the second error, "cp: missing destination....", it looks like you
didn't download the example fastqs or didn't set the "rawdir" to the folder
you kept these fastqs.
Re mypath, you would want to set it to the folder where you kept all the
files you downloaded from the github.

Sai

**Comment by whuang022nccu** [comment]
Thanks, I got it.
 I am grateful for your support!
