### ISSUE TITLE
Test data Undetermined.I2.fastq.gz maybe not complete

### ISSUE THREAD

**Issue by whuang022nccu** [masai1116/SHARE-seq-alignmentV2#2]
Dear Mr. Ma :

I am still trying to run the test data. However, while I run 

` fastp -i Undetermined_S1_I2_001.fastq.gz -o 1.Undetermined.I2.fastq.gz --reads_to_process 12100000 -S 4000000 --thread 1 -d 4 -A -G -L -Q 2
`
and got :

Error to read gzip file

That data is downloaded from the link: https://drive.google.com/drive/folders/1d0gfb7qrBL76MMh0JPRX3z9-1Wqxt0vd which is provided from the README.md

However, another one is OK

` fastp -i Undetermined_S1_I1_001.fastq.gz -o 1.Undetermined.I1.fastq.gz --reads_to_process 12100000 -S 4000000 --thread 1 -d 4 -A -G -L -Q 2
`

and output is

Read1 before filtering:
total reads: 5000000
total bases: 495000000
Q20 bases: 481912048(97.356%)
Q30 bases: 466275524(94.1971%)

Read1 after filtering:
total reads: 5000000
total bases: 495000000
Q20 bases: 481912048(97.356%)
Q30 bases: 466275524(94.1971%)

Filtering result:
reads passed filter: 5000000
reads failed due to low quality: 0
reads failed due to too many N: 0

Duplication rate (may be overestimated since this is SE data): 20.6311%

JSON report: fastp.json
HTML report: fastp.html

fastp -i Undetermined_S1_I1_001.fastq.gz -o 1.Undetermined.I1.fastq.gz --reads_to_process 12100000 -S 4000000 --thread 1 -d 4 -A -G -L -Q 2 
fastp v0.20.1, time used: 17 seconds

because of this issue, I got the error in the main process:

![image](https://user-images.githubusercontent.com/48216039/176112422-6ffd712f-1937-4796-8c9c-95f17e584ba4.png)

could you test the data for me?

Thanks for your help.

Sincerely,

**Comment by masai1116** [comment]
I run that command on the fastq but didn't see any error. Maybe try
downloading the file again?

**Comment by whuang022nccu** [comment]
Dear Mr. Ma :

I tried downloading again but still did not work.

could you help me check the size of it?

on Google Drive, It displays as 34.2MB

![image](https://user-images.githubusercontent.com/48216039/176190980-efe33c77-65c5-47e1-b77f-f091cca9d892.png)

after I download, it to the local machine I got 35 MB

![2022-06-28 21-34-09 的螢幕擷圖](https://user-images.githubusercontent.com/48216039/176192135-6ff9ecd2-64ca-4d30-b95b-03f4c21c5a45.png)

It can not use gunzip too

![2022-06-28 21-24-42 的螢幕擷圖](https://user-images.githubusercontent.com/48216039/176192646-c83345ca-9dc3-4b84-883e-84ef8567e32d.png)

the md5sum check is
**735479a0b3d157370589d3e21886d963**

![2022-06-28 21-38-44 的螢幕擷圖](https://user-images.githubusercontent.com/48216039/176192952-e428cadd-ee15-4741-b4b0-1881546de8d0.png)

the other index file Undetermined_S1_I1_001.fastq.gz  is displayed as 103.5 MB on  Google Drive, three times bigger than it, so I have a question about that.

Thanks for your help.

Sincerely,

**Comment by masai1116** [comment]
Hey Minghan,

I updated the I2 in google drive. You wanna try again? md5
is e0e232182026f3c11dcd1d56a679814a

Sai

**Comment by whuang022nccu** [comment]
Dear Mr. Ma :

Thank you so much, it works with the new data!
Sincerely,

Ming Han
