### ISSUE TITLE
rmdup.bam file not found for RNA Seq while run Igv tool

### ISSUE THREAD

**Issue by whuang022nccu** [masai1116/SHARE-seq-alignmentV2#4]
Dear Mr. Ma :

There is another issue about using Igvtool to convert .rmdup.bam to bigwig. For ATAC-seq, it works properly because the previous steps had generated "rmdup.bam" file. However, I can not find which command can generate rmdup.bam for RNA Seq in the pipeline.   
Maybe it is why I got the error of `".igv.tools.PreprocessingException: File not found: /media/whuang022/DATA/share_seq_v2_out/BMMC.RNA/BMMC.RNA.hg19.rmdup.bam"`

![2022-07-01 13-29-29 的螢幕擷圖](https://user-images.githubusercontent.com/48216039/176829883-8da0a4a9-4f00-4356-b524-3cfd7dadeacc.png)

If you have any ideas to fix this problem, please let me know.

Thanks for your help.

Sincerely,

Min Han

**Comment by masai1116** [comment]
Hi Minhan,

The pipeline doesn't generate rmdup.bam or bigwig for the RNA sample. You
can just ignore that error.

Sai

**Comment by whuang022nccu** [comment]
Dear Mr. Ma :

I got it. Thank you so much.

Sincerely,

Min Han
